<?php

namespace App\Entity;

use App\Traits\DeletedTrait;
use App\Traits\TimestampableTrait;
use App\Traits\UniqueIdTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CharacterRepository")
 * @ORM\Table(name="`character`")
 */
class Character
{
    use TimestampableTrait;
    use UniqueIdTrait;
    use DeletedTrait;

    const NAMES = [
        'Bruce Willis',
        'Calamity Jane',
        'Spiderman',
        'Marie Curie',
        'Mickey',
        'Lara Croft',
        "Sophie Marceau",
        "Marion Cotillard",
        "Florence Foresti",
        "Josiane Balasko",
        "Alexandra Lamy",
        "Mimie Mathy",
        "Louane",
        "Valérie Lemercier",
        "Line Renaud",
        "Vanessa Paradis",
        "Muriel Robin",
        "Karine Le Marchand",
        "Claire Chazal",
        "Mylène Farmer",
        "Zazie",
        "Nolwenn Leroy",
        "Catherine Deneuve",
        "Evelyne Dhéliat",
        "Laëtitia Milot",
        "Virginie Efira",
        "Sophie Davant",
        "Elise Lucet",
        "Jenifer",
        "Elodie Gossuin",
        "Amel Bent",
        "Jean-Jacques Goldman",
        "Omar Sy",
        "Dany Boon",
        "Soprano",
        "Jean Reno",
        "Francis Cabrel",
        "Teddy Riner",
        "Jean-Paul Belmondo",
        "Zinedine Zidane",
        "Jean-Luc Reichmann",
        "Jean Dujardin",
        "Thomas Pesquet",
        "Jean-Pierre Pernaut",
        "Kylian Mbappé",
        "Stéphane Plaza",
        "Stéphane Bern",
        "Renaud",
        "Guillaume Canet",
        "Fabrice Luchini",
        "Michel Sardou",
        "Christian Clavier",
        "Laurent Gerra",
        "Michel Cymes",
        "Gad Elmaleh",
        "Didier Deschamps",
        "Astérix le gaulois",
        "Bill Gates",
        "Lancelot",
        "Superman",
        "Barack Obama",
        "Tintin",
        "Rayman",
        "Mario",
        "Sonic",
        "Einstein",
        "Alice au pays des merveilles",
        "Jack Sparrow",
        "Louis Vuitton",
        "Alphonse Daudet",
        "Casimir",
        "Napoléon",
        "Bugs Bunny",
        "Johnny Halliday",
        "Lucky Luke",
        "Charlie Chaplin",
        "La Joconde",
        "Dark Vador",
        "Le génie de la lampe",
        "Haroun Tazieff",
        "Schreck","La reine d’Angleterre",
        "Claude François",
        "Gaston Lagaffe",
        "Cindy Sanders",
        "Zavatta",
        "Louis XIV",
        "Angelina Jolie", "Jamel Debbouze", "Christophe Colomb", "Carla Bruni", "Lorie", "Nicolas Canteloup", "Napoléon", "Shakespeare", "Christophe Maé", "Picasso", "John Lennon", "Amélie Poulain", "Zinedine Zidane", "Diams", "Johnny Depp", "Carla Bruni", "Brad Pitt", "Barbie",
        "Batman", "Catwoman", "Superman", "Wonder Woman","Captain America", "Daredevil", "Hulk",
        "Lionel Messi","Agatha Christie","Hubert Reeves","Picasso","Steve Job", "Louis de Funès", "Mickey", "Chantal Goya", "Cousteau", "Galilée","Dorothée","Harry Potter", "Cyril Lignac", "Archimède", "L’Abbé Pierre","Louis XIV", "Céline Dion", "Cléopâtre", "Mr Bean", "Yannick Noah", "Isaac Newton", "Le Dalaï lama", "Homer Simpson", "Jean-Pierre Pernaut", "Jules Verne", "Mac Gyver", "Mimi Mathy", "Zinedine Zidane", "Michael Jackson", "Mime Marceau", "Marilyn Monroe",
        "Florence Foresti",
        "Melanie Laurent",
        "Valerie Lemercier",
        "François Cluzet",
        "Laurent Lafitte",
        "Gérard Depardieu",
        "José Garcia",
        "Vincent Cassel",
        "Christian Clavier",
        "Kad Merad",
        "Catherine Frot",
        "Sandrine Kiberlain",
        "Jamel Debbouze,",
        "Frank Dubosc",
        "Fabrice Luchini",
        "Vincent Lindon",
        "Jean Dujardin",
        "Kev Adams",
        "Dany Boon",
        "Omar Sy",
        "Coluche",
        "Anne Roumanoff",
        "Jean-Marie Bigard",
        "Guy Bedos",
        "Aya Nakamura",
        "Dider Raoult",
        "Emmanuel Macron",
        "François Hollande",
        "Nicolas Sarkozy",
        "Jacques Chirac",
        "François Mitterand",
        "Valéry Giscard d'Estaing",
        "Georges Pompidou",
        "Charles de Gaulle",
        "Sylvain durif",
        "goldorak",
        "Vasco de Gama",
        "James Cook",
        "Thomas Edison",
        "Louis Braille",
        "Louis Pasteur",
        "Isaac Newton",
        "Archimède",
        "Pythagore",
        "Isaac Newton",
        "Booba",
        "Cyril Hanouna",
        "Nagui",
        "Michel Drucker",
        "Thierry Ardisson",
        "Laurent Ruquier",
        "Stéphane Plaza",
        "Patrick Sébastien",
        "Jean-Luc Reichmann",
        "Michel Cymes",
        "Benjamin Castaldi",
        "Stéphane Bern",
        "Jean-Pierre Foucault",
        "Karine Le Marchand",
        "Denis Brogniart",
        "Julien Lepers",
        "Sophie Davant",
        "Laurence Boccolini",
        "Yann Barthès",
        "Cauet",
        "Marco Pollo",
        "Jacques Attali",
        "Roselyne Bachelot",
        "Isabelle Balkany",
        "Patrick Balkany",
        "François Bayrou",
        "José Bové",
        "Christine Boutin",
        "Marine Lepen",
        "Christophe Castaner",
        "Winston Churchill",
        "Hillary Clinton",
        "Gilbert Collard",
        "Jean-François Copé",
        "François Fillon",
        "Rachida Dati",
        "Christian Estrosi",
        "Eric Ciotti",
        "Jean-Luc Mélenchon",
        "Olivier Besancenot",
        "Jean-Claude Gaudin",
        "Benjamin Griveaux",
        "Anne Hidalgo",
        "Nicolas Hulot",
        "Eva Joly",
        "Jack Lang",
        "Jean Lassale",
        "Jean-Marie Lepen",
        "Nelson Mandela",
        "Angela Merkel",
        "Nadine Morano",
        "Sibeth Ndiaye",
        "Charles Pasqua",
        "Ségolène Royal",
        "Dominique Strauss-Kahn",
        "Donald Trump",
        "Justin Trudeau",
        "Manuel Valls",
        "Simone Veil",
        "Eric Woerth",
        "Rama Yade",
        "Charles Aznavour",
        "Hugues Aufray",
        "Daniel Balavoine",
        "Brigitte Bardot",
        "Alain Bashung",
        "Gilbert Bécaud",
        "Amel Bent",
        "Michel Berger",
        "Beyoncé",
        "Justin Bieber",
        "Benjamin Biolay",
        "Jane Birkin",
        "Björk",
        "Bono",
        "Bourvil",
        "David Bowie",
        "Georges Brassens",
        "Jacques Brel",
        "James Brown",
        "Patrick Bruel",
        "Francis Cabrel",
        "Bertrand Cantat",
        "Mariah Carey",
        "Tracy Chapman",
        "Ray Charles",
        "Matthieu Chedid",
        "Cher",
        "Neneh Cherry",
        "Julien Clerc",
        "Kurt Cobain",
        "Phil Colins",
        "Annie Cordy",
        "Miley Cyrus",
        "Dadju",
        "Etienne Daho",
        "Dalida",
        "Dave",
        "Lana Del Rey",
        "Manu Dibango",
        "Doc Gynéco",
        "Drake",
        "Jacques Dutronc",
        "Bob Dylan",
        "Lara Fabian",
        "Mylène Farmer",
        "Faudel",
        "Fergie",
        "Ella Fitzgerald",
        "Nina Simone",
        "Claude François",
        "Nelly Furtado",
        "France Gall",
        "Charlotte Gainsbourg",
        "Serge Gainsbourg",
        "Gloria Gaynor",
        "Rihanna",
        "Maître Gims",
        "Ariana Grande",
        "Lauryn Hill",
        "Whitney Houston",
        "Julio Iglesias",
        "Mary J. Blige",
        "Janet Jackson",
        "Mick Jagger",
        "Marianne James",
        "Elton John",
        "Janis Joplin",
        "Phillipe Katerine",
        "Alicia Keys",
        "Khaled",
        "Lenny Kravitz",
        "Lady Gaga",
        "Francis Lalanne",
        "Serge Lama",
        "Laetitia Larusso",
        "Cyndi Lauper",
        "Avril Lavigne",
        "Marc Lavoine",
        "Maxime Le Forestier",
        "Michel Leeb",
        "John Lennon",
        "Annie Lennox",
        "Nolwenn Leroy",
        "Lio",
        "Lomepal",
        "Jennifer Lopez",
        "Louane",
        "Madonna",
        "Marilyn Manson",
        "Bob Marley",
        "Mireille Mathieu",
        "Mika",
        "Nicki Minaj",
        "Bernard Minet",
        "Moby",
        "Gilbert Montagné",
        "Alanis Morissette",
        "Jim Morrison",
        "Claude Nougaro",
        "Pascal Obispo",
        "Florent Pagny",
        "Vanessa Paradis",
        "Passy",
        "Stomy bugsy",
        "Dr. DRE",
        "Snoop Dog",
        "50 cent",
        "Eminem",
        "Pierre Perret",
        "Katy Perry",
        "Edith Piaf",
        "Michel Polnareff",
        "Prince",
        "Otis Redding",
        "Lionel Richie",
        "Diana Ross",
        "Henri Salvador",
        "Michel Sardou",
        "Hélène Ségara",
        "Shakira",
        "Shaggy",
        "Shy'm",
        "Alain Souchon",
        "Britney Spears",
        "Bruce Springsteen",
        "Stromae",
        "Dider Super",
        "Taylor Swift",
        "Sebastien Tellier",
        "Justin Timberlake",
        "John Travolta",
        "Tina Turner",
        "Boris Vian",
        "Laurent Voulzy",
        "Will.I.Am",
        "Robbie Williams",
        "Pharrell Williams",
        "Bill Withers",
        "Wyclef Jean",
        "Stevie Wonder",
        "Michaël Youn",
        "Zazie",
        "Catherine de Médicis",
        "Marie-Antoinette d'Autriche",
        "Georges Jacques Danton",
        "Maximilien de Robespierre",
        "Sean Connery",

    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * Character constructor.
     */
    public function __construct()
    {
        $this->uniqueId=$this->generateUniqueId();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}
